version: '3'

services:
  frontend:
    build: epr_frontend/build/
    container_name: frontend
    depends_on:
      - 'backend'
    ports:
      - '3001:3001'

  backend:
    build: epr_backend/
    container_name: backend
    depends_on:
      - 'database'
    ports:
      - '3000:3000'

  database:
    build: epr_tracker_db
    container_name: appdb
    volumes:
      - myappdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"

# Persists data across deployments so data isn't lost
volumes:
  myappdata:
    driver: local
